### ISSUE TITLE
undefined method 'default_card' for

### ISSUE THREAD

**Issue by smpetrey** [code-and-effect/effective_orders#12]
Hey guys! So far I have been following your installation instructions and documentation and it has been fantastic. I recently ran into a small issue though (although I'm a noob at Rails so it could be my fault). When processing a payment from the cart I get to step 2 of payment (in this case with Stripe):

`/orders/stripe_charge`

The payment clears with Stripe, however right afterward I get this flash message and it doesn't complete the order:

`Unable to process order with Stripe. Your credit card has not been charged. Message: "undefined method `default_card' for #<Stripe::Customer:0x007ff8c6813488>"`

Is this an issue with the gem, or am I missing something? Any help would be great!

**Comment by matt-riemer** [comment]
Hey @smpetrey 

Thanks for your interest in effective_orders!!

We developed this gem inhouse to handle our Stripe, Moneris and PayPal payment processing, along with Carts, Orders and all that good stuff :)

I think the line you're running into issues on is here:

https://github.com/code-and-effect/effective_orders/blob/master/app/models/effective/customer.rb#L45


Which is a bit of a head scratcher for me.  The `Stripe::Customer` thats throwing the error is the model that comes from the stripe-api gem itself.  Not a direct part of the `effective_orders` code base (still our problem tho, lol!)

The last time I looked at this Stripe stuff was on stripe gem version 1.19.0.   That's probably pretty old now.

What version of `stripe` are you using?  You can find this by looking in your `Gemfile.lock` file.

Stripe has been updating and messing around with their API gem a lot lately, and I think this may be a problem of 'works on an older version, but not the latest one'.

I am definitely interested in addressing this bug and could really dive into and investigate it sometime early next week.  

Thanks

**Comment by smpetrey** [comment]
@matt-riemer Thanks for the speedy reply and thanks for the awesome gem!

Stripe certainly has been updating their API's, along with their docs like [Stripe Connect](https://stripe.com/connect).

I'm on Stripe's latest gem version 1.25.0, so it very well could be a version issue. I'll play around with a different version tonight and get back to you!

**Comment by smpetrey** [comment]
Looks like the error continues to persist when I roll back my stripe gem to 1.19.0. I dug into Stripe's docs and it appears they changed ` cards ` and ` default_card ` to ` sources ` ` default_source ` respectively.

https://stripe.com/docs/upgrades#2015-02-18

**Comment by matt-riemer** [comment]
This has been resolved. Thanks @smpetrey
